#!/usr/bin/env python3
"""Render Ticket Specification v5 templates and the AI authoring adapter."""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "reference" / "issue-templates-v4"
TARGET_DIR = ROOT / "reference" / "issue-templates-v5"
AI_SOURCE = ROOT / "reference" / "ai" / "ticket-authoring-v4.md"
AI_TARGET = ROOT / "reference" / "ai" / "ticket-authoring-v5.md"
TEMPLATES = (
    "epic.md",
    "story.md",
    "bug.md",
    "security.md",
    "documentation.md",
    "testing.md",
)
SOURCE_HEADER = "<!-- Generated by tools/render_ticket_assets_v4.py. Do not edit manually. -->"
TARGET_HEADER = "<!-- Generated by tools/render_ticket_assets_v5.py. Do not edit manually. -->"
INSERT_BEFORE = "## Delivery contract\n"

NULL_INCREMENT = """## Product increment

```yaml
product_increment: null
```

"""

EPIC_INCREMENT = """## Product increment

```yaml
product_increment:
  kind: <product|release>
  subject_identity: "<product|system>:<stable-id>"
  stage: <product-stage>
  readiness_target: <1..9>
  assessment: null
```

<!-- Use product_increment: null when this Epic is not a Product-/Release-Epic increment. -->

"""

AI_APPENDIX = """

## Product/System Readiness v1

Every v5 ticket MUST contain exactly one `## Product increment` section with one fenced YAML
object whose root key is `product_increment`. Use `product_increment: null` unless a Product- or
Release-Epic deliberately declares a readiness increment.

For a non-null increment, the agent MUST author `kind`, stable `subject_identity`, Product Stage,
and Readiness Target. The Subject Identity MUST resolve to `.product-readiness.yml`. Product Stage
and TRL are orthogonal: `mvp` may target TRL 9, `production` implies no TRL, and neither dimension
may be inferred from the other.

Candidate, Assessed, Established, Preservation, Requalification, current, and actual readiness are
derived state. The agent MUST NOT author them into the ticket as authoritative metadata. The
`assessment` field is only an exact artifact reference to derived evidence.

Before completing a Product-/Release-Epic with a Readiness Target, the agent MUST require an exact
assessment reference, verify the assessment binds to the same Subject Identity, and verify its
derived Assessed Readiness meets or exceeds the authored target. Missing, stale, mismatched, or
insufficient evidence MUST fail completion closed. A target may instead be changed through the
normal reviewed ticket-governance process before completion.

Product/System Readiness is independent from security, risk, exposure, data, and criticality
classification. TRL 9 MUST NOT be interpreted as secure, low risk, security approved, or low
criticality.
"""


def render_template(name: str) -> str:
    text = (SOURCE_DIR / name).read_text(encoding="utf-8")
    if SOURCE_HEADER not in text or INSERT_BEFORE not in text:
        raise RuntimeError(f"unexpected v4 template structure: {name}")
    text = text.replace(SOURCE_HEADER, TARGET_HEADER, 1)
    increment = EPIC_INCREMENT if name == "epic.md" else NULL_INCREMENT
    return text.replace(INSERT_BEFORE, increment + INSERT_BEFORE, 1)


def render_ai_adapter() -> str:
    text = AI_SOURCE.read_text(encoding="utf-8")
    if SOURCE_HEADER not in text or "# Ticket authoring adapter v4" not in text:
        raise RuntimeError("unexpected v4 AI adapter structure")
    text = text.replace(SOURCE_HEADER, TARGET_HEADER, 1)
    text = text.replace(
        "# Ticket authoring adapter v4",
        "# Ticket authoring adapter v5",
        1,
    )
    return text.rstrip() + AI_APPENDIX + "\n"


def expected_outputs() -> dict[Path, str]:
    outputs = {TARGET_DIR / name: render_template(name) for name in TEMPLATES}
    outputs[AI_TARGET] = render_ai_adapter()
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated files differ from their canonical rendering",
    )
    args = parser.parse_args()

    mismatches: list[str] = []
    for path, expected in expected_outputs().items():
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                mismatches.append(path.relative_to(ROOT).as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    if mismatches:
        print("Generated Ticket Specification v5 assets are stale:")
        for path in mismatches:
            print(f"- {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
