#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "reference" / "ai" / "development-workflow-v7.md"
TARGET = ROOT / "reference" / "ai" / "development-workflow-v8.md"
V7_HEADER = """<!-- Generated by tools/render_development_workflow_assets_v7.py.
Do not edit manually. -->"""
V8_HEADER = """<!-- Generated by tools/render_development_workflow_assets_v8.py.
Do not edit manually. -->"""

EXTENSION = """
## Contract-first Delivery v1

Development Workflow v8 uses declaration schema v9, Ticket Specification v4, Repository
Documentation v2, and Contract-first Delivery v1.

For `delivery.applicability=required`, the agent MUST preserve this sequence:

1. Design Contract exists and is independently reviewable;
2. Test Contract derives from it and is itself qualified;
3. exact Contract references are resolved and frozen at `Status/Ready`;
4. Implementation proceeds against that frozen Contract Set;
5. Conformance Evidence evaluates the exact Implementation/deployed artifact; and
6. `Status/Done` is allowed only after valid Evidence exists.

A planned implementation MAY exist before upstream artifacts are finished and MAY use a real
`work_item` with `artifact: null`. The agent MUST NOT invent a future artifact revision. At the
Ready transition every required Design and Test Contract reference MUST resolve to a stable
artifact locator plus an exact revision and/or digest.

Test Contract qualification validates the contract rather than requiring the future product to be
green. It MUST establish assertions, fixtures/states, deterministic parameters, provenance, an
executable or reproducible harness, a controlled negative case, and fail-closed behavior. The agent
MUST NOT use `skip`, `xfail`, implicit baseline acceptance, or unbounded/materially over-broad
tolerances to mask absent implementation.

Before `Status/Ready`, the agent MUST verify separately tracked Design/Test Contract work items are
Done, all Test Contracts are qualified, all exact contract identities are resolved, and the
resulting Contract Set is recorded. Before `Status/In Progress`, it MUST revalidate the frozen set.

Invalidation propagates downstream:

- Design Contract change -> Test Contract qualification, Implementation qualification, and Evidence;
- Test Contract change -> Implementation qualification and Evidence;
- Implementation revision change -> prior Evidence.

Stale qualification MUST block forward transitions, merge, and Done. Historical Evidence MUST be
retained rather than rewritten. The affected implementation SHOULD move to `Status/Blocked` when a
safe provider transition exists.

A required implementation pull request MUST fail Contract-first validation when the frozen set is
missing/stale/unresolved, required contract work reopened, or the pull request changes the Design
Contract, Test Contract, or qualifying baseline merely to make the same implementation pass.
Legitimate contract evolution requires explicit new revisions and downstream requalification.

Evidence MUST bind exact Design Contract, Test Contract, and Implementation revisions and—where
runtime behavior applies—the exact deployed artifact/revision and environment. Evidence generation
MUST NOT mutate or widen assertions, baselines, tolerances, or governing contract content merely to
obtain a green result.

Logical Contract-first gates are `contract-graph`, `test-contract-qualification`, and
`contract-conformance`. Provider adapters MUST map these logical outcomes to concrete producible
checks and fail closed when a required concrete identity cannot be produced.

Publishing Repository Standards v9 does not prove downstream enforcement readiness. A v9 consumer
MUST NOT be activated until its ticket/lifecycle/CI integrations can enforce Contract-first
semantics fail closed. Web Live-/Visual-Conformance MUST NOT be bound normatively to a specific
Maintenance implementation until its declared consumer-qualification precondition is satisfied.
"""


def render(source: str) -> str:
    result = source.replace(V7_HEADER, V8_HEADER, 1)
    result = result.replace(
        "# Development Workflow v7 AI adapter",
        "# Development Workflow v8 AI adapter",
        1,
    )
    return result.rstrip() + "\n\n" + EXTENSION.lstrip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    source = (
        arguments.root / "reference" / "ai" / "development-workflow-v7.md"
    ).read_text(encoding="utf-8")
    target = (
        (arguments.output or arguments.root)
        / "reference"
        / "ai"
        / "development-workflow-v8.md"
    )
    expected = render(source)

    if arguments.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != expected:
            print(f"Generated Development Workflow v8 adapter is stale: {target}")
            return 1
        print("Development Workflow v8 generated adapter is current")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
