#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = (
    "epic.md",
    "story.md",
    "bug.md",
    "security.md",
    "documentation.md",
    "testing.md",
)
SOURCE_TEMPLATE_ROOT = ROOT / "reference" / "issue-templates"
SOURCE_ADAPTER = ROOT / "reference" / "ai" / "ticket-authoring-v3.md"
TARGET_TEMPLATE_ROOT = ROOT / "reference" / "issue-templates-v4"
TARGET_ADAPTER = ROOT / "reference" / "ai" / "ticket-authoring-v4.md"

V3_TEMPLATE_HEADER = (
    "<!-- Generated by tools/render_ticket_assets.py. Do not edit manually. -->"
)
V4_TEMPLATE_HEADER = (
    "<!-- Generated by tools/render_ticket_assets_v4.py. Do not edit manually. -->"
)
V3_ADAPTER_HEADER = (
    "<!-- Generated by tools/render_ticket_assets_v3.py. Do not edit manually. -->"
)
V4_ADAPTER_HEADER = (
    "<!-- Generated by tools/render_ticket_assets_v4.py. Do not edit manually. -->"
)

DELIVERY_SECTION = """## Delivery contract

```yaml
delivery:
  model: contract-first-v1
  applicability: <required|not-applicable>
  rationale: <null|non-empty rationale>
  role: <design-contract|test-contract|implementation|conformance-evidence|null>
  design_contracts: []
  test_contracts: []
  evidence: []
```

"""

ADAPTER_EXTENSION = """
## Contract-first Delivery v1

Every v4 ticket MUST contain one `## Delivery contract` section with exactly one fenced YAML
object whose root key is `delivery`. The structured object, not derived labels, is the source of
truth.

The agent MUST set `model: contract-first-v1` and explicit applicability. `not-applicable` MUST
have a non-empty rationale. For `required`, the primary role MUST be one of `design-contract`,
`test-contract`, `implementation`, or `conformance-evidence`.

A planned implementation MAY reference unfinished upstream work before Ready with a real
`work_item` and `artifact: null`. It MUST NOT invent a future revision or digest. Before a required
implementation enters `Status/Ready`, every required Design and Test Contract reference MUST be
resolved to a stable locator and exact revision and/or digest.

For required work the agent MUST preserve this order:

1. resolve the Design Contract;
2. derive and qualify the Test Contract;
3. resolve exact artifact identities and freeze the Contract Set at `Status/Ready`;
4. implement without weakening the frozen Contract Set;
5. execute conformance against the exact implementation/deployed artifact as applicable;
6. record Conformance Evidence bound to the exact revisions; and
7. only then complete the implementation.

Test Contract qualification validates the contract rather than requiring the future product to be
green. It MUST include a controlled negative case and fail-closed behavior. The agent MUST NOT use
`skip`, `xfail`, implicit baseline acceptance, unbounded/materially over-broad tolerances, or an
equivalent masking mechanism to hide absent implementation.

A Design Contract change makes dependent Test Contract qualification, implementation
qualification, and evidence stale. A Test Contract change makes implementation qualification and
evidence stale. An implementation revision change makes prior evidence stale. The agent MUST
requalify rather than rewrite historical evidence.

The agent MUST NOT repair failed Conformance Evidence by changing assertions, baselines,
tolerances, or governing contract content inside the evidence step. Such a change is contract
evolution and requires a new contract revision plus downstream requalification.
"""


def render_template(source: str) -> str:
    rendered = source.replace(V3_TEMPLATE_HEADER, V4_TEMPLATE_HEADER, 1)
    marker = "## Relations\n"
    if marker not in rendered:
        raise ValueError("Ticket template is missing the Relations heading")
    return rendered.replace(marker, DELIVERY_SECTION + marker, 1)


def render_adapter(source: str) -> str:
    rendered = source.replace(V3_ADAPTER_HEADER, V4_ADAPTER_HEADER, 1)
    rendered = rendered.replace(
        "# Ticket authoring adapter v3",
        "# Ticket authoring adapter v4",
        1,
    )
    return rendered.rstrip() + "\n\n" + ADAPTER_EXTENSION.lstrip()


def render(root: Path, output_root: Path) -> list[Path]:
    source_templates = root / "reference" / "issue-templates"
    source_adapter = root / "reference" / "ai" / "ticket-authoring-v3.md"
    target_templates = output_root / "reference" / "issue-templates-v4"
    target_adapter = output_root / "reference" / "ai" / "ticket-authoring-v4.md"
    target_templates.mkdir(parents=True, exist_ok=True)
    target_adapter.parent.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for template in TEMPLATES:
        target = target_templates / template
        source = (source_templates / template).read_text(encoding="utf-8")
        target.write_text(render_template(source), encoding="utf-8")
        written.append(target)

    source_text = source_adapter.read_text(encoding="utf-8")
    target_adapter.write_text(render_adapter(source_text), encoding="utf-8")
    written.append(target_adapter)
    return written


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    if arguments.check:
        with_output = arguments.output or arguments.root
        for template in TEMPLATES:
            source = (
                arguments.root / "reference" / "issue-templates" / template
            ).read_text(encoding="utf-8")
            target = with_output / "reference" / "issue-templates-v4" / template
            rendered = render_template(source)
            if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
                print(f"Generated Ticket v4 asset is stale: {target}")
                return 1
        source = (
            arguments.root / "reference" / "ai" / "ticket-authoring-v3.md"
        ).read_text(encoding="utf-8")
        target = with_output / "reference" / "ai" / "ticket-authoring-v4.md"
        rendered = render_adapter(source)
        if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
            print(f"Generated Ticket v4 asset is stale: {target}")
            return 1
        print("Ticket Specification v4 generated assets are current")
        return 0

    for path in render(arguments.root, arguments.output or arguments.root):
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
