#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PROFILE = ROOT / "profiles" / "development-workflow-v4.json"
TICKET_PROFILE = ROOT / "profiles" / "ticket-specification-v2.json"
TARGET = ROOT / "reference" / "ai" / "development-workflow-v4.md"


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def render() -> str:
    workflow = load_json(WORKFLOW_PROFILE)
    ticket = load_json(TICKET_PROFILE)
    prefixes = ticket["branch_prefixes"]
    regular_prefixes = [
        (kind, prefix)
        for kind, prefix in prefixes.items()
        if kind.startswith("Kind/")
    ]
    prefix_lines = "\n".join(
        f"- `{kind}` -> `{prefix}/`" for kind, prefix in regular_prefixes
    )
    hotfix = prefixes["hotfix"]
    forms = workflow["branch_naming"]["forms"]
    form_lines = "\n".join(f"- `{form}`" for form in forms)

    return f"""<!-- Generated by tools/render_development_workflow_assets.py.
Do not edit manually. -->

# Development Workflow v4 AI adapter

Before creating a branch or ticket-linked pull request, the AI agent MUST read the target
repository's `.repository-standards.yml`, validate the complete released pairing, and load the
matching released Development Workflow and Ticket Specification profiles. It MUST NOT reconstruct
naming rules from memory, prompt history, an unversioned branch, or a private alias list.

Before a Forgejo branch write, the agent MUST validate the complete planned branch name, ticket
metadata, ticket kind, source branch, and branching model. Before a ticket-linked pull-request
write, it MUST validate title, head, target, and ticket-number correspondence. Validation MUST fail
closed and happen before the Forgejo mutation.

Regular branch forms:

{form_lines}

Canonical regular prefixes are generated from `profiles/ticket-specification-v2.json`:

{prefix_lines}

`fix/` is not declared and MUST be rejected. `{hotfix}/` is reserved for the explicit Hotfix path;
it MUST NOT be used as a generic alias for `bugfix/` or as a fallback when ticket kind is unknown.

Ticket-title slugs MUST match `{workflow['branch_naming']['slug_pattern']}`. A repository-qualified
branch MUST name the repository that contains the ticket.

A ticket-linked pull request title MUST use
`{workflow['pull_request_naming']['ticket_linked_title_form']}` with a non-empty summary. Its ticket
number MUST match the ticket number encoded in the head branch. The target MUST match the selected
branching model.

Automated dependency pull requests without a project ticket MAY use the contract-defined exemption
when they are explicitly identified as such. Development Workflow v4 has no legacy creation-time
cutoff exemption.

A required Forgejo naming check remains defense in depth and MUST enforce semantics consistent with
the same released profiles. It does not replace this pre-write validation.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()

    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
            print(f"Generated Development Workflow adapter is stale: {TARGET}")
            return 1
        print("Development Workflow generated assets are current")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Rendered {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
