#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PROFILE = ROOT / "profiles" / "development-workflow-v6.json"
TICKET_PROFILE = ROOT / "profiles" / "ticket-specification-v3.json"
TARGET = ROOT / "reference" / "ai" / "development-workflow-v6.md"


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def render() -> str:
    workflow = load_json(WORKFLOW_PROFILE)
    ticket = load_json(TICKET_PROFILE)
    prefixes = ticket["branch_prefixes"]
    regular_prefixes = [
        (kind, prefix)
        for kind, prefix in prefixes.items()
        if kind.startswith("Kind/")
    ]
    prefix_lines = "\n".join(
        f"- `{kind}` -> `{prefix}/`" for kind, prefix in regular_prefixes
    )
    forms = workflow["branch_naming"]["forms"]
    form_lines = "\n".join(f"- `{form}`" for form in forms)
    checks = workflow["required_checks"]
    forgejo = checks["providers"]["forgejo_gitea"]
    github = checks["providers"]["github"]

    return f"""<!-- Generated by tools/render_development_workflow_assets_v6.py.
Do not edit manually. -->

# Development Workflow v6 AI adapter

Before creating a branch or ticket-linked pull request, the AI agent MUST read the target
repository's `.repository-standards.yml`, validate the complete released pairing, and load the
matching released Development Workflow v6 and Ticket Specification v3 profiles. It MUST NOT
reconstruct contract rules from memory, prompt history, or an unversioned branch.

Development Workflow v6 incorporates Development Workflow v5 except for the new required-check
identity and provider-adapter contract. Declaration schema v7 and Ticket Specification v3 are
required.

Regular branch forms:

{form_lines}

Canonical regular prefixes remain generated from `profiles/ticket-specification-v3.json`:

{prefix_lines}

Before changing a required workflow, event, job name, or branch-protection context, the agent MUST
identify the logical quality gate and calculate the provider-specific concrete check identity.
Required-check configuration MUST fail closed when the configured context cannot be produced.

For Forgejo/Gitea Actions, the concrete status context is
`{forgejo['context_format']}`. The event is part of the identity. A change such as
`pull_request` to `pull_request_target` therefore MUST be treated as a coordinated workflow and
branch-protection identity migration. A bounded provider-supported pattern MAY abstract only the
intended event suffix; it MUST NOT permit unrelated workflows or jobs to satisfy the gate.

For GitHub, a normal Required Status Check is `{github['normal_context_format']}` and a reusable
workflow check is `{github['reusable_context_format']}`. The event trigger is not part of the
Required Status Check identity. The agent MUST NOT invent a Forgejo/Gitea event suffix for GitHub.

A `pull_request_target` workflow runs in the base-branch trust context. The agent MUST NOT configure
it to execute, source, import, build, test, lint, or otherwise run pull-request-controlled code.
Use it for policy, metadata, and repository-governance operations that do not execute untrusted PR
content. Code-validation gates MUST use an execution model that actually validates PR content with
an appropriate untrusted-code boundary.

The agent MUST verify the new concrete identity, update workflow and protection consistently,
reject stale unproducible required contexts, preserve the logical gate, and retain rollback evidence
until qualification succeeds.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()

    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered:
            print(f"Generated Development Workflow adapter is stale: {TARGET}")
            return 1
        print("Development Workflow v6 generated assets are current")
        return 0

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Rendered {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
