#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROFILE_PATH = ROOT / "profiles" / "ticket-specification-v1.json"
GENERATED_HEADER = (
    "<!-- Generated by tools/render_ticket_assets.py. "
    "Do not edit manually. -->\n\n"
)

FAMILY_DETAILS = {
    "epic": (
        "Describe the target outcome, measurable success, boundaries, and child-ticket "
        "structure. Do not assign an Estimate/* label."
    ),
    "story": (
        "Select exactly one compatible kind: Feature, Enhancement, Refactoring, "
        "Maintenance, or Research. Add the kind-specific details required by the standard."
    ),
    "bug": (
        "Provide environment, reproduction steps, expected behavior, actual behavior, "
        "evidence, and regression validation."
    ),
    "security": (
        "Provide affected asset, attack surface or trust boundary, threat, affected "
        "versions, impact, mitigation, and validation. Do not expose secrets or personal data."
    ),
    "documentation": (
        "Provide audience, affected source of truth, required corrections or additions, "
        "examples, links, and validation."
    ),
    "testing": (
        "Provide coverage gap, risk, test level, assertions, fixtures or data, and "
        "determinism requirements."
    ),
}


def load_profile(root: Path) -> dict[str, object]:
    path = root / "profiles" / "ticket-specification-v1.json"
    return json.loads(path.read_text(encoding="utf-8"))


def template_body(family: str, profile: dict[str, object]) -> str:
    defaults = profile["defaults"]
    details = FAMILY_DETAILS[family]
    estimate = (
        "Not applicable: Epics MUST NOT have an Estimate/* label."
        if family == "epic"
        else "Estimate/<1|2|3|5|8|13>"
    )
    return GENERATED_HEADER + f"""# {family.title()} ticket

<!-- Default assignee: {defaults["assignee"]} -->
<!-- Default priority: {defaults["priority"]} -->
<!-- Default status: {defaults["status"]} -->

## Context

<!-- Explain the current situation and why the ticket exists. -->

## Goal

<!-- Define the observable outcome. -->

## Scope

### In scope

- <!-- Concrete deliverable -->

### Out of scope

- <!-- Explicit non-goal -->

### Affected components

- <!-- Repository, module, interface, data, operations, or user journey -->

## Requirements

- <!-- Use uppercase BCP 14 keywords for normative requirements. -->

## Acceptance criteria

- [ ] <!-- Observable completion criterion -->

## Work-type details

{details}

## Relations

### Parent

- None

### Blocked by

- None

### Blocks

- None

### Related

- None

## Validation

### Tests or research validation

<!-- State automated tests, research evidence, or justified alternative validation. -->

### Documentation

<!-- Name affected documentation or provide a concrete no-impact justification. -->

## Impact assessment

### Security

No impact: <!-- Replace classification and explanation as required. -->

### Compatibility

No impact: <!-- Replace classification and explanation as required. -->

### Deployment

No impact: <!-- Replace classification and explanation as required. -->

## Estimate

{estimate}
"""


def ai_adapter(profile: dict[str, object]) -> str:
    defaults = profile["defaults"]
    estimates = profile["label_categories"]["estimate"]["values"]
    kinds = profile["label_categories"]["kind"]["values"]
    kinds_text = ", ".join(kinds)
    estimates_text = ", ".join(str(value) for value in estimates)
    return GENERATED_HEADER + f"""# Ticket authoring adapter v1

Before creating, changing, classifying, or closing a ticket, the AI agent MUST determine the
released Ticket Specification version declared by `.repository-standards.yml` and MUST load the
matching adapter. It MUST NOT reconstruct rules from memory, an unversioned branch, or an older
conversation.

The agent MUST validate the complete proposed ticket before any write.

Defaults:

- assignee: `{defaults["assignee"]}`;
- priority: `{defaults["priority"]}`;
- status: `{defaults["status"]}`.

Required label cardinality:

- exactly one `Kind/*`;
- exactly one `Priority/*`;
- exactly one `Status/*`;
- at least one `Area/*`.

Allowed kinds: {kinds_text}.

Implementable Ready leaf tickets MUST have exactly one estimate from:
{estimates_text}. Epics MUST NOT have an estimate.

The agent MUST render the correct family template and preserve every required heading. Direct
blockers MUST be standalone references in `### Blocked by`. `Parent`, `Blocks`, and `Related` MUST
NOT be treated as direct blockers.

Missing factual content MUST NOT be invented. Unknown facts MUST be marked explicitly and MUST
prevent `Status/Ready` when they affect readiness, validation, documentation, security,
compatibility, deployment, scope, or dependencies.

After ticket creation or a direct-blocker change, the agent MUST trigger
`workboard_forgejo_issue_dependency_sync` for the affected ticket with `STATE=all`.

For repository creation, the agent MUST ask whether a `develop` branch is used. It MUST write the
selection to `.repository-standards.yml`. Normal Jenkins Multibranch Pipeline projects MUST use
`^(main|develop|PR-[0-9]+)$`.

In the single model, regular branches MUST start from and merge to `main`. In the integration
model, regular branches MUST start from and merge to `develop`; promotion from `develop` to `main`
MUST use a manually created and manually merged release pull request. A Hotfix MAY branch from
`main`, MUST merge to `main`, and MUST then be reintegrated into `develop`.
"""


def render(root: Path, output_root: Path) -> list[Path]:
    profile = load_profile(root)
    template_root = output_root / "reference" / "issue-templates"
    ai_root = output_root / "reference" / "ai"
    template_root.mkdir(parents=True, exist_ok=True)
    ai_root.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for family in ("epic", "story", "bug", "security", "documentation", "testing"):
        path = template_root / f"{family}.md"
        path.write_text(template_body(family, profile), encoding="utf-8")
        written.append(path)

    adapter = ai_root / "ticket-authoring-v1.md"
    adapter.write_text(ai_adapter(profile), encoding="utf-8")
    written.append(adapter)
    return written


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    output = arguments.output or arguments.root
    for path in render(arguments.root, output):
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
